# function_app.py was automatically generated by the Azure Functions VS Code extension when you created a new Python Azure Function project 
# with a Timer Trigger template. It acts as the Azure serverless entrypoint file where Azure registers triggers, schedules, and executable 
# function logic for cloud execution.
#Below code is connecting azure.functions time trigger to my build_faiss_index() function which is responsible for building the FAISS vector index from historical incident data. The timer trigger is set to run every Saturday at 2 AM, ensuring that the vector index is refreshed weekly with any new incident data added to the HistoricalIncidents.csv.
import logging
import azure.functions as func

from src.retrieval.faiss_index import (
    build_faiss_index
)

from src.storage.blob_storage import (
    download_blob,
    upload_blob
)

app = func.FunctionApp()


@app.timer_trigger(
    schedule="0 0 2 * * 6",
    arg_name="myTimer",
    run_on_startup=False,
    use_monitor=False
)

def refresh_vector_index(
    myTimer: func.TimerRequest
) -> None:

    logging.info(
        "Starting semantic memory refresh..."
    )

    download_blob(
        "HistoricalIncidents.csv",
        "data/HistoricalIncidents.csv"
    )

    build_faiss_index(
        "data/HistoricalIncidents.csv"
    )

    upload_blob(
        "data/vector_store/historical.index",
        "historical.index"
    )

    upload_blob(
        "data/vector_store/metadata.pkl",
        "metadata.pkl"
    )

    logging.info(
        "Semantic memory refresh completed successfully."
    )