from fastapi import FastAPI #FastAPI is used to: expose REST APIs, receive external requests, allow enterprise systems to interact with your workflow. This becomes: the external communication layer.

from src.graph.workflow import app as workflow_app #Imports the compiled LangGraph workflow application from workflow.py. This app object is: workflow.compile()


app = FastAPI(
    title="Incident Intelligence & SLA Copilot"
)# Creates the FastAPI application object. This initializes: the REST API server. The title appears in:Swagger docs,API metadata,interactive API UI


@app.post("/analyze-incident") #Defines a POST API endpoint at /analyze-incident. This is the external interface for triggering incident analysis. External systems will send incident data to this endpoint.
def analyze_incident(payload: dict):#Defines the API handler function. When a request is received at /analyze-incident, this function is called with the request body parsed as a dictionary (payload). This payload contains: incident details and metadata sent by the external system. The function will: extract relevant data from the payload, initialize workflow state, invoke the LangGraph workflow, and return the final alert payload generated by the workflow.
                                    #FastAPI automatically converts incoming JSON (incident data is sent in json format) into Python dictionary format.

    initial_state = {         #Creates the initial LangGraph shared workflow state. This is VERY important. Because LangGraph workflows operate using: shared state propagation. This dictionary becomes: IncidentState used throughout the graph.

        # =================================
        # INCIDENT METADATA
        # =================================
        "incident_number":
            payload.get("incident_number"),

        "short_description":
            payload.get("short_description", ""),

        "description":
            payload.get("description", ""),

        "urgency":
            payload.get("urgency", ""),

        "state":
            payload.get("state", ""),

        "opened_at":
            payload.get("opened_at", ""),

        "sla_due":
            payload.get("sla_due", ""),

        "assignment_group":
            payload.get(
                "assignment_group",
                ""
            ),

        "business_service":
            payload.get(
                "business_service",
                ""
            ),

        "cmdb_ci":
            payload.get(
                "cmdb_ci",
                ""
            ),

        # =================================
        # WORKFLOW INITIALIZATION
        # =================================
        "normalized_text": "",

        "retrieved_candidates": [],

        "retrieval_confidence": 0.0,

        "confirmed_matches": [],

        "possible_matches": [],

        "match_summary": "",

        "progress_pct": 0.0,

        "sla_total_hours": 0.0,

        "sla_elapsed_hours": 0.0,

        "sla_remaining_hours": 0.0,

        "alert_type": "NONE",

        "governance_flags": [],

        "grounding_confidence": "UNKNOWN",

        "llm_calls": 0,

        "execution_path": [],

        "processing_logs": [],

        "final_alert_payload": {}
    }

    # Execute workflow
    result = workflow_app.invoke( #This is where: LangGraph workflow execution begins. The complete shared state is passed into: workflow.py. Then LangGraph: executes nodes,propagates state,performs routing,updates workflow state automatically. This is the orchestration handoff point.
        initial_state
    )

    return result[
        "final_alert_payload"
    ] #Returns final operational intelligence response back to API caller.


#Steps to run the API server and test the endpoint:
# uvicorn src.api.api:app --reload --port 8010
# http://127.0.0.1:8010/docs
# expand /analyze-incident